### ISSUE TITLE
review by @vuntz

### ISSUE THREAD

**Issue by aspiers** [SUSE/compute-ha-training#5]
@vuntz Please can you review the material so far, taking into account [the issues I already filed](https://github.com/aspiers/compute-ha-training/issues)?

Review either via http://aspiers.github.io/compute-ha-training/ or [these instructions](https://github.com/aspiers/presentation-template#how-to-use).

**Comment by aspiers** [comment]
Of course, the above URL changed to http://suse.github.io/compute-ha-training/ since the repository transfer.

**Comment by vuntz** [comment]
Overall, this is pretty good!

Small comments:

- I'd say it's relatively safe to assume that people will know about batch, so you can go quickly on these slides

- shared-storage-needed : make it clear that glance shared storage is only required if not using swift, ceph, etc.

- verify-shared-storage: s/set up/setup/ ?

- boot-vm: you can actually use names and not IDs for nearly everything, iirc (except neutron network, maybe)

- verifying-node-recovery: `grep` command for NovaEvacuate is wrong

- I'd probably add a slide to mention that evacuation can succeed, but the instance might not be restarted because of other issues (like the glance shared storage bit which can be missing for some people) -- in short, troubleshooting this is "just" troubleshooting the issue where an instance doesn't boot.
